// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtBOfKFG4M6MOIt03AvRNT2rBqjF0ZaRk',
    appId: '1:707178950810:web:7e537936b6342a457daf23',
    messagingSenderId: '707178950810',
    projectId: 'bidishatravel1',
    authDomain: 'bidishatravel1.firebaseapp.com',
    storageBucket: 'bidishatravel1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrS0VUTX7MKrF6nrbLmnlSH1tjevlr5bE',
    appId: '1:707178950810:android:e480a638d33b6ebc7daf23',
    messagingSenderId: '707178950810',
    projectId: 'bidishatravel1',
    storageBucket: 'bidishatravel1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwSKALRmctaj4txBpVpwJJsuW_HVsZCVs',
    appId: '1:707178950810:ios:a398196492f4a1a77daf23',
    messagingSenderId: '707178950810',
    projectId: 'bidishatravel1',
    storageBucket: 'bidishatravel1.appspot.com',
    iosClientId: '707178950810-r0jju2fcoha1ja5ugpj4hu9d1l0gvo87.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelblog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwSKALRmctaj4txBpVpwJJsuW_HVsZCVs',
    appId: '1:707178950810:ios:a398196492f4a1a77daf23',
    messagingSenderId: '707178950810',
    projectId: 'bidishatravel1',
    storageBucket: 'bidishatravel1.appspot.com',
    iosClientId: '707178950810-r0jju2fcoha1ja5ugpj4hu9d1l0gvo87.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelblog',
  );
}
